### ISSUE TITLE
Build fails for Android (Ionic) : error: cannot find symbol

### ISSUE THREAD

**Issue by kevinnivek** [wf9a5m75/phonegap-googlemaps-plugin#582] opened 2015-07-31 13:28 UTC
I have been trying to build the plugin for my Ionic Android project for the past few days. I have tried troubleshooting, debugging and ruling out potential issues.

I have now decided to create a blank new project to test the build of this plugin for Android, which is still failing with fatal errors.

Here are the preliminary troubleshooting steps I took : 

* Install/Update Android APIs (API22 and API21 x86 Google)
* Tested the workaround illustrated in issue #576 
* Tested all suggestions in issue #512 
* Tested google play services v23 suggested in issue #456 

I've installed, tried different versions of Cordova and Ionic (Cordova v5, v4, v3 & Ionic v1.6, v1.5). I've updated my android SDK many times and confirmed that everything I need is installed.

My current Ionic version is

    $ ionic -v
    1.6.3

My current Cordova version is 

    $ cordova -v
    5.1.1

Installed plugins : 
```
$ ionic plugin list
com.google.playservices 23.0.0 "Google Play Services for Android"
com.googlemaps.ios 1.9.2 "Google Map iOS SDK for Cordova"
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
plugin.google.maps 1.2.5 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.4 "phonegap-http-request"
```
Steps I took to generate the error

    $ ionic start HelloMap
    $ ionic platform add android
    $ ionic plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID=XYZ --variable API_KEY_FOR_IOS=XYZ
    $ ionic build android

**Here is the full output of the build , including the errors**

```
$ ionic build android
Running command: /Users/fullname/git/username/HelloMap/hooks/after_prepare/010_add_platform_class.js /Users/fullname/git/username/HelloMap
add to body class: platform-android
Running command: /Users/fullname/git/username/HelloMap/platforms/android/cordova/build
ANDROID_HOME=/Users/fullname/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
Running: /Users/fullname/git/username/HelloMap/platforms/android/gradlew cdvBuildDebug -b /Users/fullname/git/username/HelloMap/platforms/android/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:compileLint
:com.google.playservices:hellomap882199-google-play-services_lib:copyDebugLint UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:mergeDebugProguardFiles UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:preBuild
:com.google.playservices:hellomap882199-google-play-services_lib:preDebugBuild
:com.google.playservices:hellomap882199-google-play-services_lib:checkDebugManifest
:com.google.playservices:hellomap882199-google-play-services_lib:preDebugTestBuild
:com.google.playservices:hellomap882199-google-play-services_lib:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:com.google.playservices:hellomap882199-google-play-services_lib:prepareDebugDependencies
:com.google.playservices:hellomap882199-google-play-services_lib:compileDebugAidl
:com.google.playservices:hellomap882199-google-play-services_lib:compileDebugRenderscript
:com.google.playservices:hellomap882199-google-play-services_lib:generateDebugBuildConfig
:com.google.playservices:hellomap882199-google-play-services_lib:generateDebugAssets UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:mergeDebugAssets
:com.google.playservices:hellomap882199-google-play-services_lib:generateDebugResValues UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:generateDebugResources
:com.google.playservices:hellomap882199-google-play-services_lib:mergeDebugResources
:com.google.playservices:hellomap882199-google-play-services_lib:processDebugManifest
:com.google.playservices:hellomap882199-google-play-services_lib:processDebugResources
:com.google.playservices:hellomap882199-google-play-services_lib:generateDebugSources
:com.google.playservices:hellomap882199-google-play-services_lib:compileDebugJava
:com.google.playservices:hellomap882199-google-play-services_lib:processDebugJavaRes UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:packageDebugJar
:com.google.playservices:hellomap882199-google-play-services_lib:compileDebugNdk
:com.google.playservices:hellomap882199-google-play-services_lib:packageDebugJniLibs UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:packageDebugLocalJar
:com.google.playservices:hellomap882199-google-play-services_lib:packageDebugRenderscript UP-TO-DATE
:com.google.playservices:hellomap882199-google-play-services_lib:packageDebugResources
:com.google.playservices:hellomap882199-google-play-services_lib:bundleDebug
:prepareAndroidComGooglePlayservicesHellomap882199GooglePlayServices_libUnspecifiedDebugLibrary
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJava/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:15: error: cannot find symbol
import org.apache.cordova.ScrollEvent;
                         ^
  symbol:   class ScrollEvent
  location: package org.apache.cordova
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:138: error: cannot find symbol
    root = (ViewGroup) webView.getParent();
                              ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:197: error: cannot find symbol
          webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
                 ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:206: error: cannot find symbol
          webView.setBackgroundColor(0);
                 ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:663: error: cannot find symbol
      ScrollEvent scrollEvent = (ScrollEvent)data;
      ^
  symbol:   class ScrollEvent
  location: class GoogleMaps
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:663: error: cannot find symbol
      ScrollEvent scrollEvent = (ScrollEvent)data;
                                 ^
  symbol:   class ScrollEvent
  location: class GoogleMaps
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:789: error: cannot find symbol
    webView.setVisibility(View.GONE);
           ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:807: error: cannot find symbol
        webView.setVisibility(View.VISIBLE);
               ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:879: error: cannot find symbol
          divTop - webView.getScrollY(),
                          ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/GoogleMaps.java:881: error: cannot find symbol
          divTop + divH - webView.getScrollY());
                                 ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:53: error: cannot find symbol
    this.root = (ViewGroup) webView.getParent();
                                   ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:55: error: cannot find symbol
    webView.setBackgroundColor(Color.TRANSPARENT);
           ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:57: error: cannot find symbol
      webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
             ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:132: error: cannot find symbol
    int scrollY = webView.getScrollY();
                         ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:180: error: method removeView in class ViewGroup cannot be applied to given types;
    frontLayer.removeView(webView);
              ^
  required: View
  found: CordovaWebView
  reason: actual argument CordovaWebView cannot be converted to View by method invocation conversion
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:191: error: no suitable method found for addView(CordovaWebView)
    root.addView(webView);
        ^
    method ViewGroup.addView(View,int,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View) is not applicable
      (actual argument CordovaWebView cannot be converted to View by method invocation conversion)
    method ViewManager.addView(View,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:200: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                               ^
  symbol:   method getScrollX()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:200: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                                                     ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:214: error: no suitable method found for removeView(CordovaWebView)
    root.removeView(webView);
        ^
    method ViewGroup.removeView(View) is not applicable
      (actual argument CordovaWebView cannot be converted to View by method invocation conversion)
    method ViewManager.removeView(View) is not applicable
      (actual argument CordovaWebView cannot be converted to View by method invocation conversion)
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:221: error: no suitable method found for addView(CordovaWebView)
    frontLayer.addView(webView);
              ^
    method ViewGroup.addView(View,int,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,LayoutParams) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View,int) is not applicable
      (actual and formal argument lists differ in length)
    method ViewGroup.addView(View) is not applicable
      (actual argument CordovaWebView cannot be converted to View by method invocation conversion)
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:261: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:266: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:292: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
/Users/fullname/git/username/HelloMap/platforms/android/src/plugin/google/maps/MyPluginLayout.java:303: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
24 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.702 secs

/Users/fullname/git/username/HelloMap/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/fullname/git/username/HelloMap/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/fullname/git/username/HelloMap/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/fullname/git/username/HelloMap/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/fullname/git/username/HelloMap/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/opt/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by Slavrix** [comment] 2015-07-31 16:15
try installing from phongap plugin registry
https://build.phonegap.com/plugins/3447

its forked off the Nipher fork wich works for cordova 5
https://github.com/Nipher/phonegap-googlemaps-plugin

**Comment by kevinnivek** [comment] 2015-07-31 21:18
That seemed to resolve the build failures, though now I'm seeing this in the console when trying to start the app : 

     "Google Play Services is not available.", source: file:///android_asset/www/plugins/plugin.google.maps/www/googlemaps-cdv-plugin.js (115)

**Comment by kevinnivek** [comment] 2015-07-31 21:24
Actually if i switch my emulator to Google API 19 instead of 22, it appears to work. Is this fork not tested with API 22 yet?

**Comment by jheissat** [comment] 2015-08-04 14:24
Unfortunately, on my side, the app is crashing with this solution on android. I installed the version from https://build.phonegap.com/plugins/3447. It's correctly compiling but when I run it on a device the app is crashing.

**Comment by Slavrix** [comment] 2015-08-04 14:30
Try debugging the crash through adb logcat since your seeing this on android, it should give you some information about the crash.

**Comment by jheissat** [comment] 2015-08-04 15:00
Thanks for the tip !!

Indeed I can now see that the issue is related to "java.lang.NullPointerException" at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:716).

Could it be related to Maps marker specifications which have changed ?


 
E/AndroidRuntime(13504): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(13504): Process: com.appyrise.placy, PID: 13504
E/AndroidRuntime(13504): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(13504): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(13504): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(13504): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(13504): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(13504): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(13504): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(13504): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(13504): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(13504): Caused by: java.lang.NullPointerException
E/AndroidRuntime(13504): 	at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:716)
E/AndroidRuntime(13504): 	at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:683)
E/AndroidRuntime(13504): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(13504): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(13504): 	... 4 more
W/ActivityManager( 1292):   Force finishing activity com.appyrise.placy/.MainActivity

**Comment by jheissat** [comment] 2015-08-04 15:22
Ok I get it ... this is related to this one... 
 https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/537

This should be fixed in menusito build. 

Thanks again

**Comment by Jerome2606** [comment] 2015-08-14 11:40
I have the same problem ... And what we need to take a fork version from 5 months to make this work ?

Why not submit a pull request on the master branch ?? We loose all the futures changes

**Comment by obetomuniz** [comment] 2015-08-14 14:00
@here Try this... https://github.com/obetomuniz/ionic-gmaps

**Comment by chakkrachak** [comment] 2015-08-19 10:10
Hi ! Thanks for your effort in keeping this plugin alive !

I tried following the steps to build https://github.com/obetomuniz/ionic-gmaps but my map does not show.

When I check the console output, I am having this : 
>No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.(anonymous function) @ plugins/cordova-plugin-console/www/console-via-logger.js:173
>
>Uncaught ReferenceError: plugin is not defined

Did I miss a step ?

Thanks :)

**Comment by chakkrachak** [comment] 2015-08-19 12:15
OK, allowing everything like tomorrow does not exist work : https://github.com/apache/cordova-plugin-whitelist

It removes the first error. 

I'm checking for the "plugin is not defined" problem

**Comment by chakkrachak** [comment] 2015-08-19 13:15
OK there was a problem in automatically retrieving the plugin if we were in cordova 5.1.1 : https://issues.apache.org/jira/browse/CB-9212

Now it works.

Thanks for the plugin @obetomuniz !

**Closed** 2015-08-30 23:01 UTC

**Comment by gorbachevski** [comment] 2016-03-01 10:27
Hi @chakkrachak and all users!
The issue with "plugin is not defined"  is still there. Who has the solution of this problem?
I used Ionic framework, and my **cordova** version is **6.0.0**

There are links for opened discussion at Ionic forum https://forum.ionicframework.com/t/using-google-maps-cordova-plugin/4456/111

**Comment by haldun313** [comment] 2016-05-30 15:05
"plugin is not defined" error is because of the deviceready event is not fired, you should call plugin inside the device ready function
