### ISSUE TITLE
Problem Plugin FacebookConnect and GoogleMaps for iOS and Android

### ISSUE THREAD

**Issue by cesargomez33** [wf9a5m75/phonegap-googlemaps-plugin#293] opened 2014-11-11 15:28 UTC
Hi,

I'm using your api on GoogleMaps for Phonegap but when installed a facebook plugin its not working.

http://plugins.cordova.io/#/package/com.phonegap.plugins.facebookconnect

I need to work on iOS and Android platform 

Can you help me please!!!

**Comment by wf9a5m75** [comment] 2015-02-19 17:14
@cesargomez33 Any update for this?

**Comment by cesargomez33** [comment] 2015-02-19 17:49
@wf9a5m75 i tried that cordova-facebook but i did not can!!!

**Comment by wf9a5m75** [comment] 2015-02-19 17:54
@cesargomez33 Could you describe the problem in more detail?
So what is the error? Build error or running error?
What is the error message?
Please post the whole error log.

**Comment by wf9a5m75** [comment] 2015-02-24 01:58
@cesargomez33 I tested "com.phonegap.plugins.facebookconnect", but I could not reproduce your issue at least iOS.

```
$ cordova plugin list
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 21.0.0 "Google Play Services for Android"
com.googlemaps.ios 1.9.2 "Google Map iOS SDK for Cordova"
com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
plugin.google.maps 1.2.4 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.0 "phonegap-http-request"
```

```
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <title>Google Maps Plugin for Cordova</title>
    <script src="js/jquery.min.js"></script>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript">
    $(document).on('deviceready', function() {
      
      var map = plugin.google.maps.Map.getMap($("#map_canvas")[0]);
      map.on("map_ready", function() {
        alert("MapReady!");
      });
      $("button").click(function() {
        facebookConnectPlugin.login(["public_profile"],onSuccess, onFailure);
      });
    });
    function onSuccess() {
      alert("success");
    }
    function onFailure(message) {
      alert(message);
    }
    </script>
    <style type="text/css">
      button {
        margin: 20px;
      }
      html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map_canvas {
        margin: 5%;
        width: 90%;
        height: 90%;
      }
    </style>
  </head>
  <body>
    <div id="map_canvas" ><button>Facebook login</button></div>
  </body>
</html>
```
![issue_293_ios](https://cloud.githubusercontent.com/assets/167831/6341921/7265dfbc-bb85-11e4-8f32-c10d9490a5de.gif)

**Comment by wf9a5m75** [comment] 2015-02-24 02:17
I couldn't reproduce your problem for Android, too.
![issue_293_android](https://cloud.githubusercontent.com/assets/167831/6342087/32f4c034-bb88-11e4-9b4a-e74784076f94.gif)

**Comment by wf9a5m75** [comment] 2015-02-24 02:20
@cesargomez33 
Could you describe your problem?
Or could you share your project with me?

If there is no update for a while, I will close this issue.

**Comment by wf9a5m75** [comment] 2015-02-24 02:30
Or you can download the project files that include this plugin and com.phonegap.plugins.facebookconnect plugin.

https://github.com/wf9a5m75/issue_293

Change the `API key`, `APP_ID`, and `APP_NAME` in `plugins/android.json` and `plugins/ios.json` files.

https://github.com/wf9a5m75/issue_293/blob/master/plugins/android.json#L92
https://github.com/wf9a5m75/issue_293/blob/master/plugins/android.json#L92
https://github.com/wf9a5m75/issue_293/blob/master/plugins/android.json#L130-L131

https://github.com/wf9a5m75/issue_293/blob/master/plugins/ios.json#L162
https://github.com/wf9a5m75/issue_293/blob/master/plugins/ios.json#L184
https://github.com/wf9a5m75/issue_293/blob/master/plugins/ios.json#L206
https://github.com/wf9a5m75/issue_293/blob/master/plugins/ios.json#L210-L211

**Comment by wf9a5m75** [comment] 2015-02-26 17:28
I close this issue at once, because there is no update.
If you have additional information, just post here, and I will open this issue.

**Closed by wf9a5m75** 2015-02-26 17:28 UTC
Labels: need more information
