### ISSUE TITLE
Base64 images for map marker icon not displaying on v1.2.5 [$100]

### ISSUE THREAD

**Issue by derekcaneja** [wf9a5m75/phonegap-googlemaps-plugin#547] opened 2015-06-19 00:28 UTC
Since updating the version of the plugin from v1.2.4 to v1.2.5, using a base64 image for the map marker icons either does not display or displays the default marker icon.

I have been generating the icons using canvas.toDataURL() which was working perfectly on v1.2.4.

The upgrade was necessary to fix a bug with the map plugin interfering with the splash screen.

**Comment by duckspeaker** [comment] 2015-06-20 04:24
I created a simple demo showing this seems to be working in 1.2.5: 
https://github.com/duckspeaker/phonegap-googlemaps-plugin-test

I also posted a message on Bountysource (https://www.bountysource.com/issues/22426730-base64-images-for-map-marker-icon-not-displaying-on-v1-2-5-100/developers), but realize this issue would need to be closed for completion and is also the best place to keep a conversation going.

**Comment by cosmith** [comment] 2015-06-25 09:07
This is probably related to #537. I fixed it by changing the call to `privateInitialize` in `GoogleMaps.java` that was failing silently. 

I tested this after applying my fix (https://github.com/cosmith/phonegap-googlemaps-plugin/commit/900951bd524b91ed85d53d072764c056131d85a7) and it works where it was failing before.

```
            map.addMarker({
                position: position,
                icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACUAAABACAYAAACdp77qAAARb0lEQVR42s1ZB3hUVdqOmFVRWdQFXYFgKIKACIKCC1JUUCwUC80VERGlI4h0BFkpAlIjAdIIIXV6730m0zLJlEzKpJJeSaUqvPvd2RXkd/1tFM/zvM+de86553u/cr5TJuQPlMcI0wlHu3T5GyesRw/xI2E92CH3hB6jutmE8N8zKIDfTiT0zg7LRw0ZLF02592CQ/v2tadGHYPVaIRFr4eZJwV/VwSOHv727PrVnxU8P3SwvFPnB1YyBG8GqV5h3bof2fD52ha1UAhbUhwqM9LBlLMmLy4XVIIp7RYfWpL0QEMrKlxW2JNiEPfVJiyZO6etT99+kTRO7xtFat2kOUObM6VqtAntQNMF1JcUwcZKQKXDhZoENRrVmajxetDozcX54io0lZTBmnwCmfwUuLmJKHMY4edosGLuguYOoX9Z/UdIdQp7tBsnLv44fOVpuHy2DZWSdDS5A8g1aKA8vg9nystxrrQalxrOwZvGgTXpBLL1CrgVQjg4SXDykuFgn0IWvTf4c9CUm4PDWzegV88wHo1//28lFTbo8T4uQexR4PIVNKu8qFM5cOUCY6VSpO7ZgMRd65AuPIUY1/uIzl4A3bqFUK5fD4eUAxsnEQ5+ahBOIQvm1BMQR+6GQ5iKfJUI/GOHMHTAE06S8+ivJXVvv/CebkF0BDxyLgIWI85IHGgUWVEXCKC5vhYelRRX2i8iz2gGS7IGm839wXWvhoMrhU2QArsw7RoEqbCRG/0mLVoKS5Fj1MKvFkFKHhgycICX5HX+RVI9unc/JWWloibHg8pAHiryc9FQWIQqn4/e89FYWIw6jgl1Mhu+az9HxNVQsyORlSuDQ6tGOrnMJmJdBwsRq/b50SzPQJXHBwuXhXydBimRB9CzezfOL5FauG/nV2BKrcaJi4VVqC8vw4ldn0OZFAWLmI2yzCy0qFxot+Wg1JMFkzAFZnYqyoh4ptMCEzcJ6WL2dTDyk1HszcSlMy2o8ORAJTkCkXw3Csx6bF+/Gh06dFj1c6S6zXj7zUafSY0KZxYqo6VokNtRVVgAk5iDdBkPBkEKvQfQWHoaDSUl8FkNMFKcmJQCeGOOw/TtweBvi5R7HQzUx2czoNXgR0NmNg44JoEj/gpWsQg+kxJvT36tncllPyHVvevfDwcy/KjIy0ZDcTHOBcpxsaoRHoseeooNM5FiYCB3mEgQ8zSSFYL1Vi1Mc96DbPYsmNI1VMdl6q99Q/18djNqs3IQoPSgscSgxJsNi0IAl1YK1oljoLCJ+r+kui15+Z0259FI7F4xHVaJBDmUgzItOpiVQhhpYJOcfxXMu/HquwAG0tbwwouQPj8GBouaqbvWRrNRJ0qDnqyd5TRDkHQMbqkM3zmLUe71QSthw5uuxbz3Zp1jrHWVVI9efT/dveJjpOxdB5OaB55yH/iKvdDJODDQwEbFz0NvUMBycC/KVq1ByaKl0G7fBoNR8d92YfApTomGTpyK9txSVLmzUZrrQ6PNRzHpIVIcZJhUiIs8iAcfeHD9D6TueHPaNE0ZzS60AfmlBmw3DkesdjG0YhJKpHSMAMovBuVPoSWr5dhN8FOM5ZUUw8BnQyPn/adNzqd2Pn3Ph8/hRFtGEZrdeWgLlMFFMaancQ2MJ1TiIF4Y97yR4cOQenLrxo01lxz5OH1CgiuN7WhtaYDLZELA50VLfT0yrSYoSSO9SvwTGNUSyOVipKSmQSgSITnlFAykgIYEOm1GuF026KQSyAzRSAksR3VWBlr1Xqi4CZBTbOqUwb5B127cuK6G+DzFkPokJvLIpcv+MjTJM4LJMk+pAi4Cl8rrSLt81FNuspm1UJNWOrXkOliMKkQdPQyBWAKeQIS9e3bCZJDDTjOzJTOAVm8BHOkWpKh2IFm7Bb5MF/zujOD6WEC/9RoZQYlzFVXgf3P8+9C7794Qcn+n+6UpSSdxtrkFDafLUGa1Y9WLA5CwZx1q1XacjuDhQkk1sn1ZkJMbNBoJ1GoxtFppEGqyis6oo0Amy4mEUGhVkJIFHA4TWlx5aMrMg4Vmp1alhFGjg5Ti1E5tbUYvzrkKYXFowFNE4UJNE6T7I9C58/3ikLCwHsUJibHQkICKokJcOd1Ai2cAx75cjKhNC3GhqAo1+YVQkHC5SgitXgGDQQUlEdPoZDBadYiJOIRF/xiNj0aNxq4tX0BNwa8jmCxaODIsMNv0UGpJGZ0USo0YVnJrqd8Pv9UKjvRbsP2bUEEZf+eimXi8b7/CkN69e51OoxVdRzPAkq6nDwwoyM8BU6q9flxsakY6ETATkfrqalQWFKCtvoGsJIeKSOnsRrAjD+Gbvv3xdXgfHN+4FjqnmQjIISElsj2ZaM8uRj65Sq6RQqfTQ0bjWRxmBAwmJOxcg2aaJDVGOzIVKvTv90R7SM+eYaWJaRSc6ToyvQwiGsjhsqLJX4Dy4yK0WP0oK8qFWS3EhbIaVCaqcD6nBI21NZBTTKlICQVtWcR/+ztEHf8Kzt5d0GSYoSKLSohEPk2WdoMHtYEiyMhSLON+yCgEnC4XLmVUwCcUodrpxSV3ESmqQrce3StCunbtaomMiYSRNFYalFAQZGSBxvwitKoyiEApucAGOQV0TYYH9Sk6tLsD8GS7g/1UdgMEJ6Jgm/sB7P98D6d2bae64FjULoeerN9KM/i8vxbqrMM4aJwOrc4KoSUOhpIjOOsrQZsrH7mFOYhNjEN4eLgmpMMdd2zatX/392ZXOhQkWM7EC6G6ohwl+Xkoo12m2qwNCmltaERdQREaK6sgEqVCTHGooqDlx0ejQshHrUKKpEPfQG7RMmMFISLiAbcbFzR+BPLV4BqSiKwWB3RzEG/7HC0+yl1ZeXD73dh5YA863tPxEJOpRn269rMms9tOuYRIGdWQEUQUM2K9EiLSVkr1MkaIQQ2FSQMZPXlSDli8U5BoyVpmPeppx9DocYNHOUtC39E4QUh0CthcdvgDORCJeRCrFCgI5MHv8UFldKCmuB6BeB4yVDxs3bGjmVLUhOCm7vWpk10a0lhGAv8XxAYiR6SE9JSa1AQNFOkGyM3Uxrgoy0l5pxDNxYWQmA2QGJTUpmW+DT4lRE5I37PVInBEiWi2+vC9vRgqFw9S9z74nSq0kcWWzJjjubpNfiw8/HACP41cYYbUrL0OEhrY5ExHVdlp2N1OiBjtiYzkv+0ySpKydCNq7FbUWNMh1BNRRhmLDpL/fE918qACZeR6b4YdVfn5KKakqnAIsM/4FiwVSZS03ej3SNiRH+8Sxn62eT1M2Zk0IA1EAzIQM6BZ2UBBf07mpHRQCIFZS/XX+sjtJvA0CsgmTIT0H88jTcCFkOpF1E9gIZArk2kx1lICPe8oxnlvGdrySqAhoglKKbxEDnmNiNl/CCF33jHxx6TuHDVujFtKSU1MmovS9VfBkCgPFOJMBu00i4rAM6mvaxcTKa6J0smLEyB+ZiRYcgm4RMZEM7YyrwB6lw0Cqx5ySpTeAi3ys4U4q6XEaTNB7zShuIRmucOP18e95Gd4/JgUMwvnb96zA3p/FgSkqZAECq0ERrCN4oeZnc70a20MSAExgc1OgWrqNEjHv4jk2CikUvDn+3MAWz4ysz3gmMly5OK9xrch952E3UcK0kbygsGLi7VnsCNyP0I6hCz+X9vhu4Y/NzJHyFjLYQ5qyyGrCEgoAz6RIBARY5BMEHRKFkkFSNj1FQSDh4DTPRyxX24Gm5cGJcWfldZLVYYVfFJOQO5jW+REUI9EgwJOnxutzBnSlYGhI4YFSP49P3dweHXp+jVQUWzZsrNQUV1FrtGCy7iRyP4EmeQadjJOHYuAZMx4cPsNRDzt01kJceBn2cCmeORZf/jWBDPlq9qaapg9rqCirrJCfLXjXwyLN//fI1Z4n948m92Gi5V1QF0TGqproKT44KSTtWym6yB0kWAhB/FESjxsBLjhfRG7fy+SWckQUNsP/ThEQE4KtOUWo1VEs7SoBOIsO+LlQgwcOEj8aw6jfZZ89HHbeRWdaE4pcK6qFhpyBZtxod10HQSUcFmcFMSejIH0mefA7fU44mKPIfFkLPhEgkd9mO/SKBREGRa0FJSiVZ+JyuJSKHPdmPbuLOYU0/fXkGKy/KKo1VsBa35QKxHFDoeZ+g7zdeB7nEiOj8EpVhIkI0eB1bM34k/FIT7yMDiZVnDIbQqyWENjA4y+TMjpt8nvRnZ1Odbv3YnQ0NAVv+mCo2/fPqL8LA9w5QoUmQ6wyA1chyUIntMCtt0MFglJovNeVPRRCJ9+Bvw+/REdGQF2HG19qT2jIA/ny6pxNjMf3zU0w5zjoW+siJaJ0Kd/P/nvuXXp8drUKY1q0ozNkHGmXwWLBIqzHCg/U4+mhjo0tLegrbQE7adL0XKuHefPtaGZEDhdghaLF+URXDS4c6Eia4kp5bw8bUojjd/z995PzVn8xUaoi3KDxDhEiEEKWU3n9+CXSlExrQQVdahx+nClpR1ZVWVYuu0LRurcP3Rp1r1nWFqkmAcJY3oixKa8k0oEpV4Xrlz+Dq11tairr0NzTTXN1CpKI5Woo3WyrakJUpsFYpokMurrrTiNKKkQ3R/rybsRN3ndXpz8eqM41xuMoSAy7eCQsA3Ll2PRmLH4cOLLmP/SBMyjU/I0ei5+bhTmTHwFe1KTwPa5kEqK8HLcmPDm1GZm/b9Rd54fr/p6O+TFeUgjAWyKpxRPBmZNnYp3Bw3G+iFPY/azIzFrxEisGzocC4aPwIQnn8IWCnhhrgeyojys2beHkbbsht4OP/HUYEuCRQ8uuSKNSYwFfmzdshkznxqCGWPGYTpZbMrYcZhPJ5oZo8fglRHPYQcd3STUL5HSyaDhTzuZbHOjr6xHv79qBWQlAaQSqbSAH6zDB3GyTz9sJ1dFTnoVCcOexX4iePC115FMFjtBMaSoKsWHaz9nJL1wU+7Rw/v25R/XKMCldTE1Pxusb/aAR66KXr4MJ+fNg2jIMCTNmo3Yjz6CdPAwpHFYiLGbKSf1l93My/1n565eBWlxACl5PiTRwTORscoHHyBm1iwcW7Ec3E8+wck330ICWU5CF//ztm9jpIy7maRCBgwdojxhNYFFs5EzezYSX54ETe/+iH/1NcS+NwdJM2dBTgtz8uQpSF6yBP0nTjDe7L9BmPL2SppJwkAOTpKrjs+ciVgidGLhQhz9cguOLV2C6HfegXTZMmx+YiBCOnacdStI3Tt+1owyrlYFPgX2UYqlU5s2IpVcyaEZd4zIpdB9umD3Lkx54MFqpv+tIBXy8OAn9+3fuAHKQUMQvXQpTtLJOGHJUkjDeiFu8SKkfjAPXy9YgB4PPnTkZv+Lda106PD8x+PGgTdlGmJoBkYc3I+4FSsQQTEWv3YNkvbuwQfz5wXTwC0jRSV0YpeuBdEH9oFFwRwzfToi1q5FFF0JxQu44FPwj+3fr4T63X0rSYX06NLl4PZ/bYNs8lSwmNjavBkJM2Yi7uABxFNsDQq96yjT75aSuuvuu9/4eP6HYL8xGfFvvYNoWny/3bYVSRIhVj49jA6Wd06+5aSodHp12LC6KIqhIxRXqStXIoqeyV9+iXHDn6kPuf/eh24HKWaRTjy88lPE22njt3ULWGPHY/eazzFgwkscpv22kPpr578u2Db8WSR9sRmJCxdBT6eZjW+8gU6PPLz0tpGiMvC9mTO+SywrxsklixFP2f39V165HBIaOuR2kvrLhHlziziHDiCCFuLYw4fw0uyZp5lUcDtJhYzo1o3+vd2A2KwMHNy8CQPGjBEy9beVVOdOnTZu27YNqthY7KNtzEOPPbbxtpOi8uqyz1bBPuEVbH60B0Luu2/G7Sd1110Dlo8Z+71w/kf45/jxF0PuDH3iz0Dqvpe7Plx5ks/F7EmTyqim4+0nRWXiwEEG/rr1GDl6VDbz/qcgNWL0KO4uOpA+81AX1Z+GVLeHH17/0L33oldY2KYbQerfxcfvGvlQSLYAAAAASUVORK5CYII="
            });
```

**Comment by donmasakayan** [comment] 2015-06-26 04:01
I'm also experiencing this exact issue on iOS. Base64 markers show just fine on 1.2.4, but upgrading to 1.2.5, the markers turn into the default red marker.

@cosmith - Can you implement your fix for iOS as well?

@duckspeaker - Tested your stuff out in my project. It only works when I use a direct URL to the png file. However, using base64 (or `canvas.toDataURL()`) results in the default red icon.

**Comment by cvaliere** [comment] 2015-07-13 08:41
hi guys
any news on this subject ?
I applied @cosmith fix for Android, it works
but I'm stucked on iOS :(

**Comment by leandroz** [comment] 2015-07-22 05:51
@cosmith fixed was only about Android, the iOS code is the same. I have my own fork for Cordova Android 5.0 with @cosmith fix, i just test it and is working.
Check that your string has "data:image/" and ";base64,", "data:image/png;base64,..." (The iOS code checks that)

**Comment by cvaliere** [comment] 2015-07-22 07:18
Well, I have the same fork as you.
It indeed fixes the bug for Android.
And we realized yesterday that what was not working on iOS was that our SVG file we used to build the base64 was too big. For some strange reason, the same exact JS code produced a valid base64 on Android and an invalid one on iOS.
Now that we have changed our SVG, it works both on Android and iOS.

So I'm not sure to understand why this issue is still open ? Seems to me that everything works, doesn't it ?

**Comment by lakano** [comment] 2015-08-11 12:37
Hello everybody!
I have offered a bounty for another bug ( #536 ), and the solution need to use the Nipher fork.
Now, I also need this icon Base64 bug fixed... so there is a fork where all recent bugs are fixed please ?
Regards,

**Comment by cvaliere** [comment] 2015-08-11 14:50
Hi

Seems to me like a lot of bounties for issues that have already been solved :)

Because, in fact, both issues (#536 and #547) HAVE BEEN SOLVED. It's just that the pull requests have never been accepted, which is a shame.

So, in order to have everything work properly :
- Latest Ionic JS (1.0.1)
- Latest Ionic CLI (1.6.4)
- Latest Cordova (5.1.1)
- Latest cordova-plugin-crosswalk-webview (1.3.0-dev)
- phonegap-googlemaps-plugin with @cosmith fix and @Nipher fix ; someone already compiled the two fixes here : https://github.com/dubcanada/phonegap-googlemaps-plugin

In cordova-plugin-crosswalk-webview, add webView.setZOrderOnTop(true); in src/org/crosswalk/engine/XWalkWebViewEngine.java, line 109, like this :
```java
private void initWebViewSettings() {
        webView.setVerticalScrollBarEnabled(false);
        webView.setZOrderOnTop(true);
    }
```

And then, just enjoy. It works fine. On both iOS and Android.

NB : after building for Android, the cordova-plugin-crosswalk-webview should have automatically added in the config.xml :
```xml
  <preference name="CROSSWALK_ANDROID_VERSION" value="14+"/>
  <preference name="CROSSWALK_ANDROID_COMMANDLINE" value="––disable-pull-to-refresh-effect"/>
  <preference name="LIB_MODE" value="embedded"/>
```

**Comment by cvaliere** [comment] 2015-08-15 17:44
allo houston ?

**Comment by Telemakhos** [comment] 2015-08-17 15:16
> allo houston ?

we've got a :trollface: problem... ? 

@cvaliere You're the man... It works like a charm...

@Hirbod @wf9a5m75 Please JUST merge that stuff and stop all the plugin drama...

**Comment by Hirbod** [comment] 2015-09-01 19:58
The current master is stable and should be used instead of the forks, as they are unstable and don't work fine with 5.2.0. I will incoporate the last fixes and this plugin will be again the first station to join

**Comment by Hirbod** [comment] 2015-09-01 20:02
Crash fixed in current master. Will release a new tag later. This plugin should now be considered stable.

**Comment by Hirbod** [comment] 2015-09-01 20:07
Confirmed fix. Please cash out bounty to @cosmith

**Closed by Hirbod** 2015-09-01 20:07 UTC
Labels: bounty, bug

**Comment by cvaliere** [comment] 2015-09-01 20:21
Thanks a lot @Hirbod, happy to see this plugin back to life :)

**Comment by jperl** [comment] 2015-09-18 22:42
Just following up now that I see this is fixed. @cosmith did you ever claim the bounty, I never got an email.

**Comment by cosmith** [comment] 2015-09-19 09:10
Hey @jperl, just claimed it! Thanks :)

**Comment by jperl** [comment] 2015-09-19 13:20
:+1:

**Comment by developez** [comment] 2016-02-24 16:24
It still works in versión 1.3.9?

I do this and default red pointer is shown.

``$rootScope.map.addMarker({
                    'position': pos,
                    'title': 'hello',
                    'icon': "data:image/png;base64,..K5CYII="
                }, function(marker) {
                    marker.showInfoWindow();
                });        ``

The base64 code was taken from @cosmith .

**Comment by Hirbod** [comment] 2016-02-24 16:25
icon: {
    url: "data...."
}

**Comment by developez** [comment] 2016-02-24 16:37
@hitbod no, that neither works, I tried it.
