### ISSUE TITLE
Does not work with Geofence Plugin

### ISSUE THREAD

**Issue by Mojo90** [wf9a5m75/phonegap-googlemaps-plugin#595] opened 2015-08-25 17:26 UTC
I experienced an Issue these days on Android. Already implemented the Cordova Geofence Plugin and this Google Maps Plugin here in my App. Works on iOS like a charm. Unfortunately not on Android (see my Issue here https://github.com/cowbell/cordova-plugin-geofence/issues/77)

The problem that I encountered is that googlemaps plugin needs at least Play Services V23 to work but the Geofence Plugin works at most with V22 because it uses old Classes like "GooglePlayServicesClient" and "LocationClient". 
Does anybody have a quick clue how to fix that? Thanks :)

**Comment by Hirbod** [comment] 2015-08-30 22:54
This plugin should also work with v22 - iirc

**Comment by Mojo90** [comment] 2015-09-02 12:09
Why do I get this error then? 

No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version')

removed this plugin. 
removed playservices.
added playservices v22: cordova plugin add https://github.com/wf9a5m75/google-play-services#v22
added this plugin (1.2.8.): cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="XX" --variable API_KEY_FOR_IOS="XX"

and then get the mentioned error above. Also had a look at #512 and there @Hirbod you say that it should work with cordova 5, right?
any other thoughts?

**Comment by Hirbod** [comment] 2015-09-02 12:20
Please remove plugin, playservices and install it without manually adding playservices. 
It is included as framework now in version 1.2.8

**Comment by Hirbod** [comment] 2015-09-02 12:21
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/plugin.xml#L47

**Comment by Mojo90** [comment] 2015-09-02 12:42
Ok nice.
I tried. 

Removed as you said and added again --> Same Error.
Removed all platforms added Android. -->
Now I get the same Error in GoogleMaps-Class as I get when I tried old googlemaps plugin with V22:
The import com.google.android.gms.location.LocationSettingsRequest cannot be 
 resolved
AND
The import com.google.android.gms.location.LocationSettingsResult cannot be 
 resolved

I also have this one now: 
WARNING: Found both android-support-v4 and android-support-v13 in the dependency list.
Because v13 includes v4, using only v13.

Already deleted V4 but Error does not go away (before upgrade to 1.2.8 I didn't had this)

**Comment by Hirbod** [comment] 2015-09-02 13:11
Update cordova

sudo npm -g install cordova

And be sure you install the newest platform for android (4,1.1) and iOS (3.9.1)

**Comment by Mojo90** [comment] 2015-09-02 13:26
Did update.
Android 4.1.1
Cordova 5.2.0

Unfortunately the Error persists.

**Comment by Hirbod** [comment] 2015-09-02 13:29
Weird, just tried it and works as expected. Seems like something differs in my installation.

**Comment by Hirbod** [comment] 2015-09-02 13:30
I have google analytics plugin installed, maybe they do deliver necessary frameworks which will prevent errors on my build. (Just a fast guess)

**Comment by Mojo90** [comment] 2015-09-02 13:30
This are my Plugins. Maybe has to to with the cordova-plugin-android-support-v4 21.0.1?

com.googlemaps.ios 1.9.2 "Google Map iOS SDK for Cordova"
com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.2-dev "Notification"
cordova-plugin-geofence 0.4.1 "geofence"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-googleplayservices 19.0.1 "Google Play Services for Android"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-networkactivityindicator 0.1.1 "NetworkActivityIndicator"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserNotificationSettings"
de.appplant.cordova.plugin.local-notification 0.8.2-dev "LocalNotification"
es6-promise-plugin 3.0.2 "Promise"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.globalization 0.3.4 "Globalization"
org.pushandplay.cordova.apprate 1.1.7 "AppRate"
phonegap-plugin-push 1.2.1 "PushPlugin"
plugin.google.maps 1.2.8 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.4 "phonegap-http-request"

**Comment by Hirbod** [comment] 2015-09-02 13:39
I've deleted the v4 plugin without any problems.
I also have facebook plugin installed, but I use the better updated, less buggy https://github.com/jeduan/cordova-plugin-facebook4

Please try to install

```bash
cordova plugin add cordova-plugin-google-analytics
```

Just wan't to verify if this will prevent the bugs.

**Comment by Mojo90** [comment] 2015-09-02 13:44
Nope with Google Analytics the Error persists.

I also tried to delete v4 but dependency is de.appplant.cordova.plugin.local-notification, cordova-plugin-geofence. And I do need them. But maybe I'll try later if the deletion of them will fix this.

**Comment by Hirbod** [comment] 2015-09-02 13:45
I also tried without analytics. The plugin installs perfectly. I guess some third-party plugins playing bad here. You should check the plugin.xml of geofence and try to change it also to framework-tags

**Comment by Mojo90** [comment] 2015-09-02 13:51
mh only lib-file for Android in the Geofence Plugin is this one: <lib-file src="src/android/libs/gson-2.3.jar" /> Not sure if this can break the whole build?

**Comment by Hirbod** [comment] 2015-09-02 13:52
Just try a naked project and see if it compiles or not. I can't reproduce any of your problems here

**Comment by Mojo90** [comment] 2015-09-02 14:09
So if I create a new Project:
cordova create test
and then add the plugin.
and then open up eclipse there are a lot of unresovable type errors. 
Just like: The import com.google cannot be resolved
Because in the Lib folder now there is no Android Support V13!?
Not sure why. But like this I think you can reproduce this?

**Comment by Hirbod** [comment] 2015-09-02 14:14
```bash
> cordova create maptest
> cd maptest/
> cordova platform add android
> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#1.2.8 --variable API_KEY_FOR_ANDROID="xxxxxx" --variable API_KEY_FOR_IOS="xxxx"
> cordova run android
> cordova platform version
Installed platforms: android 4.1.1
```
Build works perfectly without any error. Eclipse works with ant, not gradle and shoud not work with new cordova/cordova-android anymore. You should use Android Studio instead.

I'm locking this issue here, as the plugin works as expected!

**Comment by Mojo90** [comment] 2015-09-02 15:48
Yes my fault, I agree this works.
But now please try to add this
> cordova plugin add https://github.com/cowbell/cordova-plugin-geofence
and then
> cordova run android
does not work for me.
Errors: 
Error:(546, 12) error: cannot find symbol method getMapAsync(<anonymous OnMapReadyCallback>)
Error:(956, 25) error: cannot find symbol variable SettingsApi

Will try to investigate. Any other had this issue before?

**Comment by Hirbod** [comment] 2015-09-03 18:45
As this is not related to our plugin, I'm going to close this. Feel free to update how you managed to fix this.

**Closed by Hirbod** 2015-09-03 18:45 UTC

**Comment by Mojo90** [comment] 2015-09-04 16:53
The Error was caused by Geofence Plugin. Pull Request to fix that issue can be found here: https://github.com/cowbell/cordova-plugin-geofence/pull/80
And the related Issue can be found here: https://github.com/cowbell/cordova-plugin-geofence/pull/80#issuecomment-137589841
