### ISSUE TITLE
Temporary scrollbar on map

### ISSUE THREAD

**Issue by MCKmecik** [wf9a5m75/phonegap-googlemaps-plugin#413] opened 2015-02-23 21:42 UTC
When I start app and create map, i can see scrollbar on the top right corner on the map (as you can see on the picture). This scrollbar is shown for a while and then it disapears.
Am I doing something wrong?

![screenshot_2015-02-23-22-32-29](https://cloud.githubusercontent.com/assets/1551864/6338152/03440af0-bbad-11e4-8354-f3a55027c200.png)

**Comment by Hirbod** [comment] 2015-02-23 21:43
Did you install the #test branch or the official master?

**Comment by MCKmecik** [comment] 2015-02-23 21:50
I installed my app where I use this plugin. Everything works great except this weird behaviour. Is it possible that this may be caused by colliding with different plugin? Because I use more phonegap plugins in my app.

**Comment by Hirbod** [comment] 2015-02-23 21:52
This is not the answer of my question. Did you use the official way or did you use the #test branch?

Please post your Plugin List.  Type

```
cordova plugin list
```
and copy your output here. I guess another plugins view is interfering here.

**Comment by MCKmecik** [comment] 2015-02-23 21:58
What do you mean official way or test branch? I don't understand.

My Plugin List:
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 21.0.0 "Google Play Service
com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin"
org.apache.cordova.contacts 0.2.15 "Contacts"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.file 1.3.2 "File"
org.apache.cordova.file-transfer 0.4.8 "File Transf
org.apache.cordova.geolocation 0.3.11 "Geolocation"
org.apache.cordova.inappbrowser 0.5.4 "InAppBrowser
org.apache.cordova.plugin.sms 0.1.0 "Sms"
org.wbt11a.nativecamera 0.1.4 "Native Camera"
plugin.google.maps 1.2.4 "phonegap-googlemaps-plugi
plugin.http.request 1.0.0 "phonegap-http-request"

**Comment by wf9a5m75** [comment] 2015-02-23 22:11
@Hirbod I think @MCKmecik is not familiar with git, because @MCKmecik 's github activity is empty.

@MCKmecik I think this issue is fixed in the test version (next coming version).
In order to use it, you need to install git command.
If you use Mac, it is already installed.
If you use Windows, install this
http://git-scm.com/download/win

Then follow the below commands:
```
$> cordova plugin rm plugin.google.maps  //remove the version 1.2.4
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=...
$> cordova run android
```

**Comment by Hirbod** [comment] 2015-02-23 22:12
@wf9a5m75 but his screenshot shows an android device, I thought your view update in #test is only iOS related?

**Comment by wf9a5m75** [comment] 2015-02-23 22:13
Oops, you are right.

Ok, could you show me your HTML code, @MCKmecik ?
You forget about the test branch.

**Comment by MCKmecik** [comment] 2015-02-24 17:19
Here is my HTML code. I am using jquery mobile and backbonejs.
Div with id="map" is where I put the google map.

```
<div data-role="content" role="main" class="ui-content no-padding-top no-padding-right no-padding-bottom no-padding-left">
    <div class="map-view">
    	<div id="map">  	    	
			
    	</div>
    </div>
</div>
```

**Comment by wf9a5m75** [comment] 2015-02-24 17:24
Thanks, and what values do you specify for the html elements?

I think some HTML elements' height over the body.

Do you use Android 4.4 or over?
If so, you can debug with Chrome inspector.
https://developer.chrome.com/devtools/docs/remote-debugging

If you share your code with me, I'll check it.

**Comment by MCKmecik** [comment] 2015-02-24 17:31
Yes I have android 4.4.2.
This behaviour is on my phone (LG optimus l9 II) when I try it on HTC Desire 500, everything is OK.

Thank you for your link, I will check it and send you some result.

**Comment by MCKmecik** [comment] 2015-02-24 18:39
I have checked it, but everything looks ok. Nothing goes over the body.
I will try to uninstall all other plugins and check it again if some other plugin collide with google maps plugin.

**Comment by wf9a5m75** [comment] 2015-02-24 18:59
Could you share your apk file with me?
I will keep yout secret.
Please send it to me: wf9a5m75@gmail.com

**Comment by wf9a5m75** [comment] 2015-02-24 20:06
Thank you for sending your apk. I checked it.
I reproduced this issue, and try to get rid of this.

test code
```html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
    <meta charset="utf-8" />
    <title>Google Maps Plugin for Cordova</title>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript">
    document.addEventListener('deviceready', function() {
      var div = document.getElementById("map_canvas");
      var map = plugin.google.maps.Map.getMap(div);
    });
    </script>
    <style type="text/css">
      html, body, #map_canvas {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="map_canvas" ></div>
  </body>
</html>
```
![issue_413](https://cloud.githubusercontent.com/assets/167831/6357998/7c268568-bc1d-11e4-9609-e586ba6370f7.gif)

**Comment by wf9a5m75** [comment] 2015-02-24 20:36
This issue is fixed.
In order to apply this patch, open `platforms/android/src/plugin/google/maps/MyPluginLayout.java` with your text editor,
then add the below lines:

Line 73
```java
scrollView.setHorizontalScrollBarEnabled(false);
scrollView.setVerticalScrollBarEnabled(false);
```

After line 193 and before line 194
```java
scrollView.setHorizontalScrollBarEnabled(false);
scrollView.setVerticalScrollBarEnabled(false);
```

After line 218 and before line 219
```java
scrollView.setHorizontalScrollBarEnabled(true);
scrollView.setVerticalScrollBarEnabled(true);
```

See: https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/fa24e534b308a30348c979ead9ab82c00be6721f


![issue_413](https://cloud.githubusercontent.com/assets/167831/6358516/234818ea-bc21-11e4-8fda-6c3da48e1052.gif)

**Closed by wf9a5m75** 2015-02-24 20:36 UTC
Labels: need more information

**Comment by MCKmecik** [comment] 2015-02-25 07:41
Thanks a lot!
