### ISSUE TITLE
Plugin forces splashscreen hiding

### ISSUE THREAD

**Issue by devfd** [wf9a5m75/phonegap-googlemaps-plugin#303] opened 2014-11-14 10:47 UTC
Hello,

```org.apache.cordova.splashscreen``` plugin allows the splash screen to stay visible until we hide it with a JS call.

But when used along with ```plugin.google.maps```, the spash screen is automatically hidden as soon as the map is starting.

Is it possible for the plugin to detect when the splashscreen is off and only then to set the webview as transparent ?

Thanks

**Comment by Hirbod** [comment] 2015-01-14 02:12
I can confirm this issue. As soon as the map init, it will kill the splashscreen.
Used ```cordova plugin add org.apache.cordova.splashscreen```

**Comment by Hirbod** [comment] 2015-01-19 06:47
@wf9a5m75 any clue what happen here?

**Comment by Hirbod** [comment] 2015-02-16 01:42
@wf9a5m75 just a litte friendly ping.

**Comment by wf9a5m75** [comment] 2015-02-16 01:43
I'll test this from now.

**Comment by Hirbod** [comment] 2015-02-16 01:43
This is the related plugin:
https://github.com/apache/cordova-plugin-splashscreen

**Comment by wf9a5m75** [comment] 2015-02-16 04:04
The below code works now using the test branch.
```js
$(document).on('deviceready', function() {
    var map = plugin.google.maps.Map.getMap($("#map_canvas")[0]);
    map.on("map_ready", function() {
        alert("MapReady!");
        navigator.splashscreen.hide();
    });
});
```

![303](https://cloud.githubusercontent.com/assets/167831/6207074/b6d27298-b54d-11e4-9b42-96ec64870b02.gif)

**Comment by Hirbod** [comment] 2015-02-16 04:06
You, Mr. Masashi, are the best! :+1:  :+1:  :+1:

**Comment by Hirbod** [comment] 2015-02-16 04:06
It's time for final 1.2.5 :)

**Comment by Hirbod** [comment] 2015-02-16 04:07
But actually, the bug was, when AutoHideSplashScreen was set to false - did you checked that fact?

**Comment by wf9a5m75** [comment] 2015-02-16 04:08
Oops, I just copied the code for description. I already checked it.

**Comment by wf9a5m75** [comment] 2015-02-16 04:10
I think the issue #242 might also fix with this patch. But I haven't tested that yet.

**Comment by Hirbod** [comment] 2015-02-16 04:13
and :+1: for dispatching version check into the background!

**Comment by Hirbod** [comment] 2015-02-16 04:25
OH NO. This is not fixed. It got more worse right now. I have a scroll layer in my view right now and I can't click anything @wf9a5m75 

I make a video.

**Comment by Hirbod** [comment] 2015-02-16 04:28
@wf9a5m75 look at the right of the simulator. You can see a scrollbar now..
https://www.youtube.com/watch?v=S216nwb6zgw

**Comment by wf9a5m75** [comment] 2015-02-16 04:40
Thank, I will check it later.

**Comment by Hirbod** [comment] 2015-02-16 04:46
Thanks. I go to sleep right now, maybe you have fixed this later, so I don't need to revert everything :)

**Comment by robinbonnes** [comment] 2015-02-16 07:44
Thanks for looking into this. 

However  the app doesn't always hide the splashscreen after showing the map. Think for example of an app which hides the splashscreen after showing a page with a button and after clicking the button it opens the map.

**Comment by wf9a5m75** [comment] 2015-02-16 08:48
I reverted the commit.

**Comment by Hirbod** [comment] 2015-02-16 13:47
Hello @robinbonnes ,

I think you misunderstood the functionality. It depends on your settings - how you want to handle this.
Actually this plugin cause the splashscreen to immediate disappear as soon as it inits, even when you've set the config to stay open until you close it by yourself. This is what Masashi fixed, but sadly the complete UI is unusable after his fix.

@wf9a5m75 any new progress?

**Comment by yedeba** [comment] 2015-02-16 20:29
Hello, I have the same problem.
I found a solution but wf9a5m75 do better, but it works.
In GoogleMaps.m:

Inside function: - (void) pluginInitialize

change:

         self.root = self.webView.superview;
         [self.webView removeFromSuperview];
         self.pluginLayer.webView = self.webView;
         [self.pluginLayer addSubview: self.pluginScrollView];
         [self.pluginLayer addSubview: self.webView];
         [self.root addSubview: self.pluginLayer];

by:

NSTimeInterval delayInSeconds = 1.2;
    
     dispatch_time_t Poptime = dispatch_time (DISPATCH_TIME_NOW, NSEC_PER_SEC delayInSeconds *);
     dispatch_after (Poptime, dispatch_get_main_queue () ^ (void) {
        
         self.root = self.webView.superview;
         [self.webView removeFromSuperview];
         self.pluginLayer.webView = self.webView;
         [self.pluginLayer addSubview: self.pluginScrollView];
         [self.pluginLayer addSubview: self.webView];
         [self.root addSubview: self.pluginLayer];
     });

This will cause a delay in the initialization of the plugin, which is the cause.

It's a start ....

Wf9a5m75 Thanks for your work.
Bye !!

**Comment by wf9a5m75** [comment] 2015-02-17 07:15
@Hirbod Did you copy the code by your hand yesterday?
I tested the yesterday's code, but it works perfectly.

https://www.youtube.com/watch?v=mqpIp9SF6JI

Confirm the below code, the output in Xcode should be 
0 = UIImageView
1 = UIActivityIndicatorView

```objc
  self.root = self.webView.superview;
  [self.webView removeFromSuperview];
  self.pluginLayer.webView = self.webView;
  [self.pluginLayer addSubview:self.pluginScrollView];
  [self.pluginLayer addSubview:self.webView];
  
  NSArray *subViews = self.root.subviews;
  UIView *view;
  for (int i = 0; i < [subViews count]; i++) {
    view = [subViews objectAtIndex:i];
    NSLog(@"%d = %@", i, view.class);    // 0 = UIImageView, 1 = UIActivityIndicatorView
    [view removeFromSuperview];
  }
  [self.root addSubview:self.pluginLayer];
  for (int i = 0; i < [subViews count]; i++) {
    [self.root addSubview: [subViews objectAtIndex:i]];
  }
```

**Comment by Hirbod** [comment] 2015-02-17 07:25
Hi @wf9a5m75 

yesterday I installed you #test repo. Directly after you pushed it. Then I made the video.

**Comment by Hirbod** [comment] 2015-02-17 07:28
Or do you mean I should copy this code now by hand? Maybe I did not understand you well.

**Comment by Hirbod** [comment] 2015-02-17 07:30
No.. I tried you code. It does not work. Again, same problem

**Comment by Hirbod** [comment] 2015-02-17 07:32
@wf9a5m75 
As you can see, I have a UIScrollView (maybe the keyboard plugin) or something else

**Comment by wf9a5m75** [comment] 2015-02-17 14:47
Ah, I see. What plugin do you use?

**Comment by Hirbod** [comment] 2015-02-17 14:48
See my last post.

**Comment by wf9a5m75** [comment] 2015-02-17 14:50
Only keyboard?

**Comment by Hirbod** [comment] 2015-02-17 14:51
I posted a big list

Von meinem iPhone gesendet

> Am 17.02.2015 um 15:50 schrieb Masashi Katsumata <notifications@github.com>:
> 
> Only keyboard?
>

**Comment by Hirbod** [comment] 2015-02-17 14:53
Once again:


```
android.support.v4 1.0.0 "Android Support v4"
at.modalog.cordova.plugin.cache 1.0.0 "Cache"
com.adjust.sdk 3.4.1 "Adjust"
com.ccsoft.plugin.CordovaFacebook 1.1.0 "CordovaFacebook"
com.google.playservices 22.0.0 "Google Play Services for Android"
com.googlemaps.ios 1.9.2 "Google Map iOS SDK for Cordova"
com.ionic.keyboard 1.0.3 "Keyboard"
com.phonegap.plugins.PushPlugin 2.2.1 "PushPlugin"
com.plugin.datepicker 0.3.22 "Datepicker"
com.ququplay.websocket.WebSocket 0.1.0 "WebSocket"
com.simonmacdonald.telephonenumber 1.0.0 "TelephoneNumber"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
de.appplant.cordova.plugin.email-composer 0.8.2dev "EmailComposer"
es.keensoft.fullscreenimage 1.0.0 "Full Screen Image"
hu.dpal.phonegap.plugins.SpinnerDialog 1.2.0 "SpinnerDialog"
hu.dpal.phonegap.plugins.UniqueDeviceID 1.2.0 "UniqueDeviceID"
nl.x-services.plugins.actionsheet 1.1.1 "ActionSheet"
nl.x-services.plugins.socialsharing 4.3.12 "SocialSharing"
nl.x-services.plugins.toast 2.0.2 "Toast"
org.apache.cordova.camera 0.3.5 "Camera"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.dialogs 0.3.0 "Notification"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
org.apache.cordova.geolocation 0.3.12 "Geolocation"
org.apache.cordova.inappbrowser 0.5.4 "InAppBrowser"
org.apache.cordova.media 0.2.16 "Media"
org.apache.cordova.network-information 0.2.15 "Network Information"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"
org.apache.cordova.vibration 0.3.13 "Vibration"
plugin.google.maps 1.2.4 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.0 "phonegap-http-request"
uk.co.whiteoctober.cordova.appversion 0.1.5 "AppVersion"
```

**Comment by wf9a5m75** [comment] 2015-02-17 14:54
Ah, ok. I found it. I couldn't see it in the e-mail, but I found it on the web page.

**Comment by robinbonnes** [comment] 2015-02-17 23:23
Hello @Hirbod,

I understand this functionality:

$(document).on('deviceready', function() {
    var map = plugin.google.maps.Map.getMap($("#map_canvas")[0]);
    map.on("map_ready", function() {
        alert("MapReady!");
        navigator.splashscreen.hide();
    });
});

But think of something like this:

$(document).on('deviceready', function() {

	// Hide splash after webpage launch
	navigator.splashscreen.hide();

	// Show map after clicking the button
	$("#mybutton").click(function() {
		var map = plugin.google.maps.Map.getMap($("#map_canvas")[0]);
		map.on("map_ready", function() {
			alert("MapReady!");
		});
	}):
});

That also prevents the splashscreen from displaying on app launch.

**Comment by wf9a5m75** [comment] 2015-02-18 07:38
@Hirbod The status bar plugin blocks the touch event. (Just let you know)

**Comment by Hirbod** [comment] 2015-02-18 07:47
Hi,

any chance that you can fix that in a generic way under the most circumstances ?

**Comment by wf9a5m75** [comment] 2015-02-18 08:18
This is not easy, because the status bar plugin generates their layer always on top.
![screen shot 2015-02-18 at 12 18 10 am](https://cloud.githubusercontent.com/assets/167831/6244114/aac7d88c-b703-11e4-8ab1-fd747467bcec.png)

**Comment by wf9a5m75** [comment] 2015-02-22 05:53
Ok, is this good for you guys?
![issue_303](https://cloud.githubusercontent.com/assets/167831/6317639/073b0edc-ba14-11e4-8a0a-be30141ba4ef.gif)

**Comment by wf9a5m75** [comment] 2015-02-22 05:54
```
$(document).on('deviceready', function() {
  var map = plugin.google.maps.Map.getMap($("#map_canvas")[0], {
    'backgroundColor': 'red'
  });
  map.on("map_ready", function() {
    alert("MapReady!");
    navigator.splashscreen.hide();
  });
});
```

**Comment by Hirbod** [comment] 2015-02-22 16:20
Sis you forgot to deactivate WebKit over scroll? Or why does the map have an bounce momentum ? And does this work with status bar plugin now? If yes, I will try the test version later and confirm if the bug is fixed

**Comment by wf9a5m75** [comment] 2015-02-22 16:22
The test branch should work with the status bar.

**Comment by yedeba** [comment] 2015-02-22 22:55
Remember that not all applications have the first screen map,
and the plugin fails also.

**Comment by Hirbod** [comment] 2015-02-22 22:57
No it won't, since you can set the config to AutoHideSplashScreen true

**Comment by yedeba** [comment] 2015-02-22 23:04
If you set AutoHideSplashScreen true, why use the splashscreen plugin ?.
What is desired is that it does not, it lasts a few seconds more and can for example do fade when it's loaded.

**Comment by Hirbod** [comment] 2015-02-22 23:06
There are some other benefits it you want to programatically show/hide it. Even though, with or without this maps plugin, if you set AutoHide to false, you need to trigger the hide() method by yourself anyway, no matter when your map is loaded first or not. It's up to your code and entry point to determine the state and hide the splashscreen.

**Comment by yedeba** [comment] 2015-02-22 23:12
I do not understand, really.
The topic of this thread is not, what the plugin hides splashscreen ?.
It always does.
If I say that not all applications have the first screen map, it is precisely the solution that has been made since the load depends directly on the map.

**Comment by Hirbod** [comment] 2015-02-22 23:16
Listen,

please read the thread carefully. There was a bug, which caused trough this plugin (it forced the splashscreen to be hidden as soon as the map was initalized (cause it was inited over the splashscreen).
This was a bug and a wrong behaviour. The map should not kill or overlay any other view (like it did with the splashscreen). Due to this bug, it caused that you couldn't see the fade progress, neither you could control when the splashscreen should be hidden, as it gots hidden asap the map was available or called trough JS.

Masashi was going to fix this bug and he did.
@wf9a5m75, Masashi, tested right now with the test branch. It works. Even with the status bar plugin. Perfect. Let's see if it will interfere with any other plugin (crossing fingers not)

**Comment by Hirbod** [comment] 2015-02-22 23:17
For now, this thread can be closed as the bug is fixed in #test branch

**Comment by yedeba** [comment] 2015-02-22 23:29
I know.
What I mean is that the plugin hides splashscreen not only when the map is initialized.
In my app always does, to initialize the application, not the map, with the plugin installed.

**Comment by Hirbod** [comment] 2015-02-22 23:30
Yeah, ok, but thats actually an error. When you update to 1.2.5, you need to call the splashscreens hide method by yourself when you've set AutoHideSplashScreen to false. 

Alternatively you could use 

```
        <preference name="SplashScreenDelay" value="10000" />
```

To add a maximum delay.

**Comment by Hirbod** [comment] 2015-02-23 00:31
@wf9a5m75 bug is fixed, I close this one here!

**Closed by Hirbod** 2015-02-23 00:31 UTC
Labels: bug

**Comment by wf9a5m75** [comment] 2015-02-23 00:33
OK, thank you for your test.
